### ISSUE TITLE
Support for WLToys v911 transmitter

### ISSUE THREAD

**Issue by oleglark** [execuc/v202-receiver#1]
Hi,
is it possible to use your library with the v911 transmitter?

I have tried, but failed to bind. I constantly get NOT_BOUND from the protocol.run() method call.

**Comment by execuc** [comment]
Hi,

This transmitter use an other 2.4G chip (A7105 ?) with an other protocol. So it's impossible with this code.

**Comment by oleglark** [comment]
Thanks for a quick answer.
I`m just wondering how it actually works. To start receiver on nRF24L01 you should specify the address of pipe that will be used. But in case of wltoys transmitters, what should I specify as a pipe when starting my nRF24L01 in a receiver mode?

**Comment by execuc** [comment]
V202 protocol use a constant p5-bytes pipe address (0x66 0x88 0x68 0x68 0x68). But transmitters switch the frequency each 8 milliseconds. I don't know if I have correctly answered the question...

**Comment by oleglark** [comment]
yes, v911 works on a same chip as nRF24L01 - A7105. But I can not find any info on how to initially bind them..after that maybe i will be able to debug and try to decode incoming data. I was thinking if transmitter actually does a broadcast initially and send bind packets everywhere.

**Comment by execuc** [comment]
nrf24L01+ and a7105 are two different chips. This code is not compatible with A7105 and the v911 protocol.

**Comment by oleglark** [comment]
ok, sorry for troubling you and thanks for quick replies. Looks like I got it all wrong. Thanks again

**Comment by execuc** [comment]
No problem. Open a new conversation if you have more questions. I have also a v911 transmitter but I never try to make a receiver because A7105 was more cheaper/difficult to use than the nrf24L01.
Actually I have plan to make an arduino receiver which works with the CX-10 (little quadcopter) transmitters. It is also use the nrf24l01 chip and the protocol is easier because it doesn't use frequency hopping.
